name: CI/CD Pipleline

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Build And Deploy Frontend
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Frontend Dependencies
        working-directory: frontend 
        run: npm install
      
      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy Frontend To Nginx
        run: |
          sudo rsync -a --delete frontend/dist/ /var/www/html/
          sudo rm -r frontend

      - name: Restart Nginx
        run: sudo systemctl restart nginx
  
  backend:
    name: Deploy Backend
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: npm install

      - name: Deploy Backend
        run: |
          sudo mkdir -p /home/ubuntu/github-actions/temp-backend/
          sudo rsync -a --delete --exclude=".*" . /home/ubuntu/github-actions/temp-backend/
          pm2 stop backend
          sudo mkdir -p /home/ubuntu/github-actions/backend/
          sudo rsync -a --delete /home/ubuntu/github-actions/temp-backend/ /home/ubuntu/github-actions/backend/

      - name: Restart Backend Services
        run: |
          sudo -u ubuntu pm2 restart backend || sudo -u ubuntu pm2 start /home/ubuntu/github-actions/backend/index.js --name backend
          sudo -u ubuntu pm2 save


  
